FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.27 AS builder

WORKDIR /src

COPY . /src

# Build
ARG TARGETOS TARGETARCH
RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg \
    CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -a -ldflags="-s -w" -o /out/tor-local-manager ./agents/tor/main.go

FROM docker.io/rinsecode/tor:0.4.9.8@sha256:8e8e8971dcd3934b570cc4cc43f85aefeac6ae5672d0666332ba5b99e05fc56a AS tor

RUN mkdir -p /app
COPY --from=builder --chmod=0555 /out/tor-local-manager /app

ENTRYPOINT ["/app/tor-local-manager"]
